function [color_stim_displays] = Generate_rand_color_displays_minSep45(Num_stim_per_trial,Num_color_trials)
%By CTGill
%Last updated: 12/29/21
%
% This Version of Generate_rand_color_displays ensures that each target
% location is selected an equal number of times for each condition. This
% differs from the original version of Generate_rand_obj_displays which
% randomly selects the target position for each trial (thus allowing
% variability in how many times targets are presented in each location
% across the different conditions).
%
% This function was created for use in vWM_Exp2.m
%
% Function uses the colorwheel matrix that Brady uploaded to OSF in the files for 
% his "The Role of Meaning in vWM..." (2021) article to generate sets of colored 
% circles stimuli for each trial. All colors in the display are a minimum of 45deg apart on
% the CIE color wheel (repicating Brady et al. 2016 and 2021). The Target
% and Foil Colors are always maximally dissimilar (i.e. 180 deg apart on
% CIE color wheel). 
%
% First, a theta angle is randomly selected (Target theta). Next, 7
% additional colors are generated by serially adding 45 degrees to the
% random target theta. The Foil is taken to be the color 180 degrees from the target.
% Then 5 of the remaining 6 colors are randomly selected to be non-target
% display colors. The location of the target is quasi random such that it
% appears in each location an equal number of times over
% all trials. 

%
% INPUTS
%
% min_separation     --> minimum degrees of seperation on the CIE color circle = 45degrees
%
% Num_stim_per_trial --> The total number of color stimuli per trial.
%
% Num_stim_per_trial --> The number of stimuli in each display of the encoding phase of the vWM task. (e.g. 6)
%
%
% OUTPUTS
%
% color_stim_displays--> a struct containing color display info.
%                        color_stim_displays.Target            --> contains the Target color in RGB.
%                        color_stim_displays.Foil              --> contains the Foil color in RGB.
%                        color_stim_displays.Study_stimuli     --> contains the RGB color of all stimuli in study display.
%                        color_stim_displays.Target_study_pos  --> contains the Target object position in study display (Pos 1 is always at the 9'oclock position and subseqent positions go clockwise).
%                        color_stim_displays.stim_theta_angles --> contains the theta angle for Target, Foil, and all study colors          
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

color_stim_displays = struct('Target',{},'Foil',{},'Study_stimuli',{},'Target_study_pos',[],'stim_theta_angles',{});

load('Brady_ColorWheel360.mat');
colorWheel = fullcolormatrix/256;

theta = zeros(1,Num_stim_per_trial);
stim_colors = zeros(3,Num_stim_per_trial);

% %create shuffled target Location Index such that in each block the target
% %will be in each potential location an equal number of times
% temp = repmat([1:Num_stim_per_trial],1,(Num_color_trials/Num_stim_per_trial/2));
% %shuffle index separately for 1st block and 2nd block then add together 
% temp1 = temp(randperm(Num_color_trials/2));
% temp2 = temp(randperm(Num_color_trials/2));
% shuffled_target_loc_idx = [temp1 temp2];

%create shuffled target Location Index such that in each block the target
    %will be in each potential location as close as possible to an equal number
    %of times. Because there are 40 trials per condition, the target will be shown
    %in 4 of the study locations 7 times and in 2 of the study locations the
    %target will only be shown 6 times.
    temp = repmat([1:Num_stim_per_trial],1,ceil(Num_color_trials/Num_stim_per_trial/2));
    %randomly select which of the 2 study locations will only be used 6 times
    locs2remove = randi([1,6],1,2);
    for i = 1:2
        idx2remove = find(temp==locs2remove(i),1,'last');
        temp(idx2remove) = [];
    end
    temp = temp(1:(Num_color_trials/2));
    %shuffle index separately for 1st block and 2nd block then add together
    temp1 = temp(randperm(Num_color_trials/2));
    temp2 = temp(randperm(Num_color_trials/2));
    shuffled_target_loc_idx = [temp1 temp2];

for trl = 1:Num_color_trials
    for i = 1:Num_stim_per_trial+2
        if i == 1
            theta(i) = randi(360);
            
            stim_colors(:,i) = colorWheel(theta(i),:)';
            targer_color = stim_colors(:,i);
            
        else
            if (theta(i-1)+45)<361
                theta(i) = theta(i-1)+45;
            else
                theta(i) = (theta(i-1)+45)-360;
            end
            stim_colors(:,i) = colorWheel(theta(i),:)';
        end
    end
    
    %Save Trial Target, Foil
    color_stim_displays(trl).Target = targer_color;
    color_stim_displays(trl).Foil = stim_colors(:,5);
    
    %Remove Foil from Display Stim Colors
    stim_colors(:,5) = [];
    theta_foil = theta(5);
    theta(5) = [];
    
    %Randomly select one theta orientation not to include 
    tmp_idx = randsample(7,1);
    stim_colors(:,tmp_idx) = [];
    theta(tmp_idx) = [];
    
    
    %randomize Target Study Position such that each target
    %location occurs an equal number of times per condition
    stim_locs = zeros(1,Num_stim_per_trial);
    stim_locs(shuffled_target_loc_idx(trl)) = 1;
    shuffled_other_stim_locs = randperm(Num_stim_per_trial);
    shuffled_other_stim_locs = shuffled_other_stim_locs(shuffled_other_stim_locs>1);
    count = 0;
    for i = 1:Num_stim_per_trial
        if stim_locs(i) == 0
            count = count + 1;
            stim_locs(i) = shuffled_other_stim_locs(count);
        end
    end
    
    %Save Encoding phase stimuli and Target Position
    color_stim_displays(trl).Study_stimuli = stim_colors(:,stim_locs);
    color_stim_displays(trl).Target_study_pos = find(stim_locs == 1);
    
    %save all theta angles
    color_stim_displays(trl).stim_theta_angles.all = theta(stim_locs);
    color_stim_displays(trl).stim_theta_angles.target = theta(1);
    color_stim_displays(trl).stim_theta_angles.foil = theta_foil;
end
